name: Page & Resume builder

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  page-resume-build:
    name: Page & Resume builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Pip
        run: |
          python -m pip install --upgrade pip
        
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qqy
          sudo apt-get -qqy install google-chrome-stable
          CHROME_VERSION=$(google-chrome-stable --version)
          CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
          CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
          sudo rm /etc/apt/sources.list.d/google-chrome.list
          export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
          curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
          export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
          curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
          chromedriver --version

      - name: Run Script
        run: |
          HOOK_INFO=$(curl -X POST $DEPLOY_HOOK)
          DEPLOYMENT_ID=$(echo $HOOK_INFO | jq -r '.result.id')
          GET_DEPLOYMENT_INFO_URL="https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/pages/projects/resume/deployments/${DEPLOYMENT_ID}"
          DEPLOYMENT_INFO=$(curl -X GET $GET_DEPLOYMENT_INFO_URL -H "X-Auth-Email: ${CF_EMAIL_ID}" -H "X-Auth-Key: ${CF_AUTH_TOKEN}")
          export STAGING_URL=$(echo $DEPLOYMENT_INFO | jq -r '.result.url')
          cd scripts && pip install -r requirements.txt && python html2pdf.py
        
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SOURCE: ${{ secrets.SOURCE }}
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_EMAIL_ID: ${{ secrets.CF_EMAIL_ID }}
          CF_AUTH_TOKEN: ${{ secrets.CF_AUTH_TOKEN }}
